[".zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto.git"
    clone.args = ["--depth=1", "--recurse-submodules"]
    pull.args = ["--depth=1", "--recurse-submodules"]
    refreshPeriod = "24h"

[".base16-shell"]
    type = "git-repo"
    url = "https://github.com/chriskempson/base16-shell"
    clone.args = ["--depth=1"]
    pull.args = ["--depth=1"]
    refreshPeriod = "24h"

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    clone.args = ["--depth=1"]
    pull.args = ["--depth=1"]
    refreshPeriod = "24h"

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"
