[".zprezto"]
    type = "git-repo"
    url = "https://github.com/sorin-ionescu/prezto.git"
    refreshPeriod = "720h"
    clone.args = ["--recurse-submodules"]
    pull.args = ["--recurse-submodules"]

[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
    clone.args = ["--branch", "v3.1.0"]

[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/0.14.0/plug.vim"
    refreshPeriod = "168h"
