# Starship configuration
# https://starship.rs/config/

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$nodejs\
$docker_context\
$aws\
$terraform\
$cmd_duration\
$line_break\
$character"""

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "

[git_state]
format = '[$state( $progress_current/$progress_total)]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[nodejs]
symbol = " "
detect_files = ["package.json", ".node-version"]

[docker_context]
symbol = " "
only_with_files = true

[aws]
symbol = " "
format = '[$symbol($profile )]($style)'

[terraform]
symbol = "󱁢 "
detect_files = [".terraform", "*.tf"]

[cmd_duration]
min_time = 2_000

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
